# Generated by Django 2.1.1 on 2018-10-17 06:57

import django.core.validators
from django.db import migrations, models
import otree_manager.om.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='name',
            field=models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(code='invalid', message='Name may only contain a-Z, 0-9, -. Dash may not be first or last.', regex='^[A-Za-z0-9](?:[A-Za-z0-9\\-]{0,61}[A-Za-z0-9])?$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 63 characters or fewer. Letters, digits and - only.', max_length=63, unique=True, validators=[otree_manager.om.models.user.CustomUsernameValidator()], verbose_name='username'),
        ),
    ]
