# Generated by Django 2.0.6 on 2018-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0003_otreeinstance_otree_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='otreeinstance',
            name='otree_participant_labels',
            field=models.TextField(blank=True),
        ),
    ]
