# Generated by Django 2.0.6 on 2018-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0004_otreeinstance_otree_participant_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='otree_participant_labels',
            field=models.TextField(default='[]'),
        ),
    ]
