# Generated by Django 2.0.6 on 2018-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0005_auto_20180909_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='otree_participant_labels',
            field=models.TextField(default="'[]'"),
        ),
    ]
