# Generated by Django 2.1.2 on 2018-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0006_auto_20180909_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='otree_participant_labels',
            field=models.TextField(default='[]'),
        ),
    ]
