# Generated by Django 2.0.6 on 2018-07-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otreeinstance',
            options={},
        ),
    ]
