# Generated by Django 2.0.5 on 2018-06-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otreeinstance',
            name='owned_by',
        ),
    ]
