# Generated by Django 2.0.5 on 2018-06-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='otree_production',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
