# Generated by Django 2.0.5 on 2018-06-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otreeinstance',
            name='enabled_plugins',
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
    ]
