# Generated by Django 2.0.5 on 2018-06-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0002_auto_20180613_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ws_channel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
