# Generated by Django 2.0.5 on 2018-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0003_user_ws_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ws_channel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
