# Generated by Django 2.0.5 on 2018-06-03 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0003_otreeinstance_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Experimenter',
        ),
    ]
