# Generated by Django 2.0.5 on 2018-06-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0003_auto_20180623_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otreeinstance',
            options={'permissions': (('can_restart', 'Can restart the oTree instance'), ('can_reset', 'Can reset otree database'))},
        ),
    ]
