# Generated by Django 2.0.5 on 2018-06-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0004_auto_20180623_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='otreeinstance',
            name='web_dynos',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='worker_dynos',
            field=models.SmallIntegerField(default=1),
        ),
    ]
