# Generated by Django 2.0.5 on 2018-06-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0004_auto_20180613_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otreeinstance',
            name='app_created',
        ),
    ]
