# Generated by Django 2.0.5 on 2018-06-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0005_remove_otreeinstance_app_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='otreeinstance',
            name='otree_admin_username',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='otree_auth_level',
            field=models.CharField(default='STUDY', max_length=200),
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='otree_production',
            field=models.SmallIntegerField(default=1),
        ),
    ]
