# Generated by Django 2.0.5 on 2018-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0005_auto_20180629_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='web_dynos',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='otreeinstance',
            name='worker_dynos',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
