# Generated by Django 2.0.5 on 2018-06-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0006_auto_20180617_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='otreeinstance',
            name='otree_admin_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='otreeinstance',
            name='otree_admin_username',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='otreeinstance',
            name='otree_auth_level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='otreeinstance',
            name='otree_production',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
