# Generated by Django 2.0.5 on 2018-06-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0006_auto_20180603_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otreeinstance',
            options={'permissions': (('can_restart', 'Can restart the oTree instance'),)},
        ),
    ]
