# Generated by Django 2.0.5 on 2018-06-29 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0006_auto_20180629_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='web_dynos',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='otreeinstance',
            name='worker_dynos',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
