# Generated by Django 2.0.6 on 2018-06-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0007_auto_20180603_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstancePlugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('core', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='otreeinstance',
            options={'permissions': (('can_restart', 'Can restart the oTree instance'), ('can_delete', 'Can delete the oTree instance'))},
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='git_repo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='instanceplugins',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dm.oTreeInstance'),
        ),
        migrations.AddField(
            model_name='instanceplugins',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dm.Plugin'),
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='plugins',
            field=models.ManyToManyField(through='dm.InstancePlugins', to='dm.Plugin'),
        ),
    ]
