# Generated by Django 2.0.6 on 2018-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0008_auto_20180604_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='verbose_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
