# Generated by Django 2.0.6 on 2018-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0008_auto_20180708_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ssh_public_key',
        ),
        migrations.AddField(
            model_name='user',
            name='public_key_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
