# Generated by Django 2.0.6 on 2018-06-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0009_auto_20180604_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstancePlugins',
            new_name='InstancePlugin',
        ),
    ]
