# Generated by Django 2.0.6 on 2018-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0010_auto_20180604_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanceplugin',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='instanceplugin',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='otreeinstance',
            name='plugins',
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='enabled_plugins',
            field=models.ManyToManyField(to='dm.Plugin'),
        ),
        migrations.DeleteModel(
            name='InstancePlugin',
        ),
    ]
