# Generated by Django 2.0.6 on 2018-06-04 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('dm', '0012_auto_20180604_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otreeinstance',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Experimenter'),
        ),
        migrations.DeleteModel(
            name='OTreeUser',
        ),
    ]
