# Generated by Django 2.0.6 on 2018-06-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0014_auto_20180604_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otreeinstance',
            name='git_repo',
        ),
    ]
