# Generated by Django 2.0.5 on 2018-06-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0015_remove_otreeinstance_git_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='otreeinstance',
            name='app_dir',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='deploy_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='otreeinstance',
            name='git_sha',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
