# Generated by Django 2.0.5 on 2018-06-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0016_auto_20180612_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='otreeinstance',
            name='app_created',
            field=models.BooleanField(default=False),
        ),
    ]
