from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import PasswordResetForm
from otree_manager.om.models import OTreeInstance, User
from otree_manager.om.forms import (
    AddUserForm,
    ChangeKeyForm,
    EditUserForm,
)

"""User Views"""

@login_required
def change_key_file(request):
    """View to change SSH key file"""
    if request.method == 'POST':
        form = ChangeKeyForm(request.POST or None, request.FILES or None, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = ChangeKeyForm()

    return render(request, 'om/user/change_key_file.html', {'form': form})


@login_required
@permission_required('om.add_users', login_url='user/login/', raise_exception=True)
def new_user(request):
    """View to add new user"""
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            nuser = form.save()
            # if a new user is created, a random password is generated by default
            # at the same time, we trigger a password reset, so the user can set their own password
            # this also emails the user about their new account.
            reset_form = PasswordResetForm({'email': nuser.email})
            assert reset_form.is_valid()
            reset_form.save(
                request=request,
                use_https=request.is_secure(),
                subject_template_name='om/emails/user_registration_subject.txt',
                email_template_name='om/emails/user_registration.html',
            )
            return HttpResponseRedirect(reverse('list_users'))
    else:
        form = AddUserForm()
    return render(request, 'om/user/new.html', {'form': form})


@login_required
@permission_required('om.delete_users', login_url='user/login/', raise_exception=True)
def delete_user(request, user_id):
    """View to delete a user account"""
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('index'))

    user_inst = User.objects.get(id=user_id)
    user_count = User.objects.all().count()
    instances = OTreeInstance.objects.filter(owned_by=user_inst)

    # Sanity checks!
    # cannot delete last remaining user on the site
    # cannot delete if instances are still associated with the account
    # cannot delete yourself
    delete_ok = user_count > 1 and instances.count() == 0 and user_inst != request.user

    if not delete_ok:
        return HttpResponseRedirect(reverse('edit_user', args=(user_id,)))
    else:
        user_inst.remove_public_key()
        user_inst.delete()

    return HttpResponseRedirect(reverse('list_users'))


@login_required
def edit_user(request, user_id):
    """Edit user details view"""
    # Only super users can edit user details
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('index'))

    # check if user can be deleted (show / hides button on detail page)
    # could potentially wrap this in a function as it is also used in delete user view above
    user_inst = User.objects.get(id=user_id)
    user_count = User.objects.all().count()
    form = EditUserForm(request.POST or None, instance=user_inst)
    instances = OTreeInstance.objects.filter(owned_by=user_inst)

    delete_ok = user_count > 1 and instances.count() == 0 and user_inst != request.user

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list_users'))

    return render(request, 'om/user/edit.html',
                  {'form': form, 'containers': instances, 'user': user_inst, 'delete_ok': delete_ok})


@login_required
def list_users(request):
    """Lists all users"""
    # only super users have access
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('index'))
    else:
        user_list = User.objects.all().order_by('last_name')
        return render(request, 'om/user/list.html', {'user_list': user_list})
